version: '2.2'

services:
  nginx:
    image: nginx:stable
    ports:
    - "${NGINX_PORT}:8888"
    networks:
      default:
        aliases:
        - magento.local
    depends_on:
    - php
    volumes:
    - "./local-ssl:/etc/nginx/ssl:ro"
    - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    - "./config/nginx/nginx.conf:/etc/nginx/nginx.conf"
    - "magento2:/var/www/html:ro"
    - "./magento/var:/var/www/html/var:ro"
    - "./magento/app/code:/var/www/html/app/code:ro"
  php:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
    - mysql
    - rabbitmq
#    command: tail -f /dev/null
    ports:
      - 9000:9000
    volumes:
    - "./config/bin/run.sh:/run.sh"
    - "./install:/install"
    - "magento2:/var/www/html:rw"
    - "./magento/var:/var/www/html/var:rw"
    - "./magento/app/code:/var/www/html/app/code:rw"
    links:
    - mysql
    - rabbitmq
  rabbitmq:
    env_file: .env
    image: rabbitmq:3.8.2-alpine
    ports:
      - 5673:5672
  mysql:
    env_file: .env
    image: mysql:5.7.25
    ports:
      - 3326:3306
    volumes:
    - magento2-mysql:/var/lib/mysql:rw,delegated
  magento-redis:
    image: 'redis:4-alpine'
    ports:
      - 6380:6379
    volumes:
      - magento2-redis:/data:rw,delegated

volumes:
  magento2:
  magento2-mysql:
  magento2-redis:
